In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [5]:
df=pd.read_csv("/content/healthcare_data.csv")

In [6]:
df.head()

,Patient_ID,Age,Gender,Blood_Type,Medical_Condition,Medical_Code,Date_of_Admission,Discharge_Date,Admission_Type,Billing_Amount
0,P0001,47,Male,AB+,Heart Disease,HEA004,2025-05-10,2025-05-16,Emergency,23218.31
1,P0002,62,Female,AB-,Diabetes,DIA001,2025-12-31,2026-01-02,Emergency,47010.56
2,P0003,36,Male,AB-,Heart Disease,HEA004,2025-11-10,2025-11-27,Emergency,39619.01
3,P0004,51,Male,A+,Heart Disease,HEA004,2023-05-02,2023-05-07,Elective,35963.71
4,P0005,30,Male,A+,Diabetes,DIA001,2024-04-11,2024-04-17,Urgent,64615.93

In [7]:
df.shape

(1000, 10)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         1000 non-null   object
 1   Age                1000 non-null   int64
 2   Gender             1000 non-null   object
 3   Blood_Type         1000 non-null   object
 4   Medical_Condition  1000 non-null   object
 5   Medical_Code       970 non-null    object
 6   Date_of_Admission  1000 non-null   object
 7   Discharge_Date     1000 non-null   object
 8   Admission_Type     1000 non-null   object
 9   Billing_Amount     1000 non-null   float64
dtypes: float64(1), int64(1), object(8)
memory usage: 78.3+ KB

In [9]:
df["Age"]

0      47
1      62
2      36
3      51
4      30
       ..
995    24
996    63
997    63
998    33
999    41
Name: Age, Length: 1000, dtype: int64

In [10]:
df["Medical_Code"]

0      HEA004
1      DIA001
2      HEA004
3      HEA004
4      DIA001
        ...
995    DIA001
996    DIA001
997    DIA001
998    DIA001
999    AST003
Name: Medical_Code, Length: 1000, dtype: object

In [11]:
df.isnull().sum()

Patient_ID            0
Age                   0
Gender                0
Blood_Type            0
Medical_Condition     0
Medical_Code         30
Date_of_Admission     0
Discharge_Date        0
Admission_Type        0
Billing_Amount        0
dtype: int64

In [12]:
df["Medical_Code"]=df["Medical_Code"].fillna('unknown')

In [13]:
df['Admission_Type']=(
    df["Admission_Type"]
    .str.strip()
    .str.title()
)

In [14]:
df['Admission_Type'].unique()

array(['Emergency', 'Elective', 'Urgent'], dtype=object)

In [15]:
df["Admission_Type"].value_counts()

Admission_Type
Emergency    381
Elective     368
Urgent       251
Name: count, dtype: int64

In [16]:
df["Date_of_Admission"]=pd.to_datetime(
    df["Date_of_Admission"]
)

In [17]:
df["Discharge_Date"]=pd.to_datetime(
    df["Discharge_Date"]
)

In [18]:
df['Date_of_Admission'].dt.year

0      2025
1      2025
2      2025
3      2023
4      2024
       ...
995    2023
996    2025
997    2023
998    2023
999    2023
Name: Date_of_Admission, Length: 1000, dtype: int32

In [19]:
df['Date_of_Admission'].dt.month

0       5
1      12
2      11
3       5
4       4
       ..
995     3
996     4
997     5
998     2
999     2
Name: Date_of_Admission, Length: 1000, dtype: int32

In [20]:
df['Date_of_Admission'].dt.day

0      10
1      31
2      10
3       2
4      11
       ..
995    16
996    17
997     8
998    11
999    10
Name: Date_of_Admission, Length: 1000, dtype: int32

In [23]:
df["stay_days"] = (df["Discharge_Date"] - df["Date_of_Admission"]).dt.days

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         1000 non-null   object
 1   Age                1000 non-null   int64
 2   Gender             1000 non-null   object
 3   Blood_Type         1000 non-null   object
 4   Medical_Condition  1000 non-null   object
 5   Medical_Code       1000 non-null   object
 6   Date_of_Admission  1000 non-null   datetime64[ns]
 7   Discharge_Date     1000 non-null   datetime64[ns]
 8   Admission_Type     1000 non-null   object
 9   Billing_Amount     1000 non-null   float64
 10  stay-days          1000 non-null   int64
 11  stay_days          1000 non-null   int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(6)
memory usage: 93.9+ KB